"""add_invitees_field_to_agents

Revision ID: 03c741585071
Revises: 352ef9652323
Create Date: 2025-09-16 08:25:43.280941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c741585071'
down_revision: Union[str, Sequence[str], None] = '352ef9652323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('invitees', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'invitees')
    # ### end Alembic commands ###
