"""rename_max_daily_appointments_to_max_slot_appointments

Revision ID: 14415f9d20fc
Revises: 3b48e4a7f421
Create Date: 2025-09-16 19:04:27.625645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14415f9d20fc'
down_revision: Union[str, Sequence[str], None] = '3b48e4a7f421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('max_slot_appointments', sa.Integer(), nullable=True))

    # Migrate data from old field to new field, changing default from 8 to 1
    op.execute("UPDATE agents SET max_slot_appointments = 1 WHERE max_daily_appointments IS NOT NULL")

    op.alter_column('agents', 'booking_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('agents', 'max_daily_appointments')

    # Set default value for the new field
    op.alter_column('agents', 'max_slot_appointments', nullable=False, server_default='1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('max_daily_appointments', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('agents', 'booking_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('agents', 'max_slot_appointments')
    # ### end Alembic commands ###
