"""Your migration message here

Revision ID: 245dfc5d8c38
Revises: 6e4ac9db370e
Create Date: 2025-09-21 06:27:32.339640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245dfc5d8c38'
down_revision: Union[str, Sequence[str], None] = '6e4ac9db370e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('agent_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('orders_board_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'agents', ['agent_id'], ['id'])
    op.drop_column('orders', 'board_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('board_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_board_id_fkey'), 'orders', 'boards', ['board_id'], ['id'])
    op.drop_column('orders', 'agent_id')
    # ### end Alembic commands ###
