"""add_booking_enabled_field_to_agents

Revision ID: 3b48e4a7f421
Revises: 03c741585071
Create Date: 2025-09-16 10:42:39.398398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b48e4a7f421'
down_revision: Union[str, Sequence[str], None] = '03c741585071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('booking_enabled', sa.Boolean(), nullable=True))
    # Set default value for existing records
    op.execute("UPDATE agents SET booking_enabled = true WHERE booking_enabled IS NULL")
    # Make the column non-nullable with default
    op.alter_column('agents', 'booking_enabled', nullable=False, server_default='true')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'booking_enabled')
    # ### end Alembic commands ###
