"""Your migration message here

Revision ID: 53da88656230
Revises: bb721c1a35d1
Create Date: 2025-09-22 10:26:38.111285

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53da88656230"
down_revision: Union[str, Sequence[str], None] = "bb721c1a35d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents", sa.Column("after_hours_behavior", sa.String(), nullable=True)
    )
    op.add_column("agents", sa.Column("after_hours_message", sa.Text(), nullable=True))
    op.add_column("agents", sa.Column("closed", sa.Boolean(), nullable=True))
    op.add_column("agents", sa.Column("closed_message", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "closed_message")
    op.drop_column("agents", "closed")
    op.drop_column("agents", "after_hours_message")
    op.drop_column("agents", "after_hours_behavior")
    # ### end Alembic commands ###
