"""Your migration message here

Revision ID: 6b5f63a21441
Revises: beb48f013a3b
Create Date: 2025-09-21 14:08:42.885305

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b5f63a21441"
down_revision: Union[str, Sequence[str], None] = "beb48f013a3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("pickup_time", sa.DateTime(), nullable=True))
    op.add_column("orders", sa.Column("special_requests", sa.Text(), nullable=True))
    op.add_column("orders", sa.Column("confirmed_at", sa.DateTime(), nullable=True))
    op.add_column("orders", sa.Column("payment_status", sa.String(), nullable=True))
    op.add_column("orders", sa.Column("payment_method", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "payment_method")
    op.drop_column("orders", "payment_status")
    op.drop_column("orders", "confirmed_at")
    op.drop_column("orders", "special_requests")
    op.drop_column("orders", "pickup_time")
    # ### end Alembic commands ###
