"""

Revision ID: 9eb93c95c1bc
Revises: f6b72e7f5436
Create Date: 2025-09-22 12:09:41.327758

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9eb93c95c1bc"
down_revision: Union[str, Sequence[str], None] = "f6b72e7f5436"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
