"""Your migration message here

Revision ID: bb721c1a35d1
Revises: 9e0c17981a35
Create Date: 2025-09-21 15:59:22.938118

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bb721c1a35d1"
down_revision: Union[str, Sequence[str], None] = "9e0c17981a35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("completed_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "completed_at")
    # ### end Alembic commands ###
