"""Your migration message here

Revision ID: beb48f013a3b
Revises: d414da133d86
Create Date: 2025-09-21 14:05:21.060218

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "beb48f013a3b"
down_revision: Union[str, Sequence[str], None] = "d414da133d86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
