"""

Revision ID: c1f74d6a4052
Revises: 9eb93c95c1bc
Create Date: 2025-09-23 06:45:21.449516

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1f74d6a4052"
down_revision: Union[str, Sequence[str], None] = "9eb93c95c1bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_users",
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("agent_id", "user_id"),
    )
    op.drop_constraint(op.f("agents_user_id_fkey"), "agents", type_="foreignkey")
    op.drop_column("agents", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agents",
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("agents_user_id_fkey"), "agents", "users", ["user_id"], ["id"]
    )
    op.drop_table("agent_users")
    # ### end Alembic commands ###
