"""add_eleven_labs_voice_support

Revision ID: ca7a9b4201b1
Revises: cd3d99730dd8
Create Date: 2025-09-19 08:02:23.042912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca7a9b4201b1'
down_revision: Union[str, Sequence[str], None] = 'cd3d99730dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('eleven_labs_voice_id', sa.String(), nullable=True))
    op.add_column('agents', sa.Column('voice_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'voice_provider')
    op.drop_column('agents', 'eleven_labs_voice_id')
    # ### end Alembic commands ###
