"""Your migration message here

Revision ID: d414da133d86
Revises: d0dfae03d2d3
Create Date: 2025-09-21 09:53:21.460800

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d414da133d86"
down_revision: Union[str, Sequence[str], None] = "d0dfae03d2d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
