"""Your migration message here

Revision ID: d8c1d7808a38
Revises: 53da88656230
Create Date: 2025-09-22 10:36:28.618731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8c1d7808a38"
down_revision: Union[str, Sequence[str], None] = "53da88656230"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("transfer_settings", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("agents", "transfer_settings")
    # ### end Alembic commands ###
