"""

Revision ID: efc8c99a114f
Revises: c1f74d6a4052
Create Date: 2025-09-23 06:57:16.167742

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "efc8c99a114f"
down_revision: Union[str, Sequence[str], None] = "c1f74d6a4052"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
